# Generated by Django 2.0.2 on 2018-02-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_nums', models.PositiveIntegerField(default=0, verbose_name='博客数目')),
                ('category_nums', models.PositiveIntegerField(default=0, verbose_name='分类数目')),
                ('tag_nums', models.PositiveIntegerField(default=0, verbose_name='标签数目')),
                ('visit_nums', models.PositiveIntegerField(default=0, verbose_name='网页访问量')),
            ],
            options={
                'verbose_name': '数目统计',
                'verbose_name_plural': '数目统计',
            },
        ),
    ]
